language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
script:
  - make test
env:
  - DJANGO=1.4.8
  - DJANGO=1.5.4
after_script:
  coveralls --verbose
