language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
script:
  - make test
env:
  - DJANGO=1.7.11
  - DJANGO=1.8.13
  - DJANGO=1.9.7
after_script:
  coveralls --verbose
